### ISSUE TITLE
Improving the UX/UI from the modal

### ISSUE THREAD

**Issue by jotapegr** [privacycloud/consent-manager-web-ext#103]
I will like to suggest some changes to the UX/UI from the modal. I hope this change will help everyone to have a better experience :)

I designed this proposal to take it into consideration:
- [Mockup Figma](https://www.figma.com/file/2xZx6wDSfb5z3m2EEv0uj8/Consent-manager?node-id=2%3A3)

The idea of this new design is to offer better information to users so we can know what is happening whit the cookies while we are surfing the web.

**Comment by sergioalvz** [comment]
Ey @jotapegr, I agree. That dynamic text is quite convenient to understand what's happening when the crown gets red 😃
