### ISSUE TITLE
Simple Easy Request 

### ISSUE THREAD

**Issue by AlfMonroe** [privacycloud/consent-manager-web-ext#84]
I click the crown icon, can you please add a 'd' to the word 'enable', that way it would read ENABLED and I'd know that it is working.   ENABLE suggests that you should click something to enable it.   Just saying.  Thanks

**Comment by victorpergo** [comment]
Thanks for the feedback @AlfMonroe! It makes totally sense. We'll make that adjustment. Regards.

**Comment by sergioalvz** [comment]
This is already in `master` and ready to be deployed as part of the `v3.1.0` release 🎉
